### ISSUE TITLE
Search Index also for restricted content?

### ISSUE THREAD

**Issue by HolyMacarony** [iMi-digital/imi-conrun#9]
Hello,  i'd like to ask whether the search indexing iterates over every frontend user to generate a compete index of restricted content too? This would be a much appreciated feature :)

Is this supposed to work with contao4?   i tried  
./imi-conrun.phar indexer:search:build --root-dir /var/www/contao4/       but i only get
"Your script is not compatible with Contao"

thank you very much!

**Comment by amenk** [comment]
It does not iterate over the frontend users - as far as I remember the implementation. 

Also we currently do not use contao 4 yet (but soon), so imi-conrun is not yet tested or ported to Contao 4 ...

Pull requests welcome :-)

**Comment by amenk** [comment]
@HolyMacarony is  this still revelant for you? otherwise we will close the issue

**Comment by amenk** [comment]
Close due to lack of feedback
